# ok
contador = 0 #O(1)
def F(n): #O(1)
    if n == 1: #O(1)
        return G(0)
    elif n % 2 == 0: #O(1)
        G(1)
        return F(n/2)
    elif n % 2 != 0: #O(1)
        G(1)
        return F(3 * n + 1)
def G(c): #O(1)
    global contador
    contador +=c
    return contador
T = int(input()) #O(1)
maior = 0 #O(1)
lista = [] #O(1)
for i in range(T): #O(T)
    periodo = [int(x) for x in input().split()] #O(1)
    for j in range(periodo[0], periodo[1]): #O(n)
        contador = 0  #O(1)
        a = F(j)  #O(1)
        if a>maior:  #O(1)
            maior = a  #O(1)
            a = 0  #O(1)
    lista += [maior+1]  #O(1)
    maior = 0  #O(1)
for x in range(T): #O(T)
    print(f'Caso {x+1}: {lista[x]}')  #O(1)
