emprestimo = float(input('valor do emprestimo - '))
juros = emprestimo + (emprestimo * 20 / 100)
print('valor do emprestimo com juros - ', juros)
parcelar = int(input('você quer parcelar em quantas vezes? '))
print(f'vc pagará {juros/parcelar} todos os meses ate acabar amg.')